GET http://localhost:3001/api/persons/

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Brwedwn",
    "number": 98765423433
}
###

DELETE http://localhost:3001/api/persons/6